import os
import markdown
from datetime import datetime

# Theme rebuilt to match the "ZERO TRACE // RED TEAM" brand mark: near-black
# background, cold silver for structural/neutral text, and a strong red
# accent (instead of the old neon-green "hacker" look) for anything that
# represents danger/risk/critical content, exactly like the logo's
# black+silver+red split.
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ZERO TRACE // RED TEAM — {target}</title>
<style>
    :root {{
        --bg: #050506;
        --panel: #0c0d10;
        --red: #e0293f;
        --red-dim: #7a1420;
        --silver: #c9ced3;
        --silver-dim: #6d7580;
        --text: #d7dadc;
        --danger: #ff3b52;
        --warn: #ffd93b;
        --border: #23262b;
    }}

    * {{ box-sizing: border-box; }}

    body {{
        background: var(--bg);
        color: var(--text);
        font-family: 'Courier New', Consolas, monospace;
        margin: 0;
        padding: 0;
        line-height: 1.65;
        background-image:
            radial-gradient(circle at 15% 0%, rgba(224,41,63,0.06), transparent 40%),
            linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px);
        background-size: auto, 24px 24px, 24px 24px;
    }}

    .header {{
        border-bottom: 1px solid var(--red-dim);
        padding: 34px 40px 26px 40px;
        background: linear-gradient(180deg, #0a0a0c 0%, #050506 100%);
    }}

    .brandmark {{
        font-size: 30px;
        font-weight: 700;
        letter-spacing: 4px;
        margin: 0 0 4px 0;
        text-transform: uppercase;
    }}
    .brandmark .zero {{ color: var(--silver); text-shadow: 0 0 10px rgba(201,206,211,0.35); }}
    .brandmark .trace {{ color: var(--red); text-shadow: 0 0 12px rgba(224,41,63,0.55); }}

    .subbrand {{
        color: var(--silver-dim);
        font-size: 12px;
        letter-spacing: 6px;
        text-transform: uppercase;
        margin-bottom: 18px;
    }}

    .header h1 {{
        color: var(--text);
        margin: 10px 0 6px 0;
        font-size: 18px;
        letter-spacing: 1px;
        font-weight: 400;
    }}

    .header .meta {{
        color: var(--silver-dim);
        font-size: 13px;
    }}

    .container {{
        max-width: 980px;
        margin: 0 auto;
        padding: 30px 40px 60px 40px;
    }}

    .panel {{
        background: var(--panel);
        border: 1px solid var(--border);
        border-left: 3px solid var(--red);
        border-radius: 4px;
        padding: 24px 28px;
    }}

    h2 {{
        color: var(--red);
        border-bottom: 1px dashed var(--border);
        padding-bottom: 8px;
        margin-top: 36px;
        font-size: 19px;
        letter-spacing: 0.5px;
    }}

    h3 {{ color: var(--silver); font-size: 16px; }}

    code, pre {{
        background: #08090a;
        color: #e8ebed;
        border: 1px solid var(--border);
        border-radius: 4px;
        padding: 2px 6px;
        font-size: 13.5px;
    }}

    pre {{ padding: 14px; overflow-x: auto; }}

    a {{ color: var(--red); }}

    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 14px 0;
    }}

    th, td {{
        border: 1px solid var(--border);
        padding: 8px 12px;
        text-align: left;
        font-size: 13.5px;
    }}

    th {{ background: #100b0c; color: var(--red); }}

    blockquote {{
        border-left: 3px solid var(--warn);
        margin: 10px 0;
        padding: 4px 16px;
        color: var(--warn);
        background: #14130a;
    }}

    .footer {{
        text-align: center;
        color: var(--silver-dim);
        font-size: 12px;
        margin-top: 50px;
        border-top: 1px solid var(--border);
        padding-top: 18px;
        letter-spacing: 2px;
        text-transform: uppercase;
    }}
    .footer .no-limits {{ color: var(--red); }}

    ::selection {{ background: var(--red); color: #000; }}
</style>
</head>
<body>
    <div class="header">
        <div class="brandmark"><span class="zero">ZERO</span> <span class="trace">TRACE</span></div>
        <div class="subbrand">RED TEAM</div>
        <h1>&gt;&gt; ZT-RECON // SECURITY ASSESSMENT REPORT</h1>
        <div class="meta">
            TARGET: {target} &nbsp;|&nbsp; GENERATED: {timestamp} &nbsp;|&nbsp; ENGINE: {model}
        </div>
    </div>
    <div class="container">
        <div class="panel">
            {body}
        </div>
        <div class="footer">
            NO TRACE. NO EVIDENCE. <span class="no-limits">NO LIMITS.</span><br>
            Generated by ZT-RECON — AI-Powered Automated Recon &amp; Exploitation Orchestrator.<br>
            For authorized security testing use only.
        </div>
    </div>
</body>
</html>
"""


def generate_html_report(target, ai_markdown_text, output_dir="./reports", model_name="unknown"):
    """Converts the AI-generated Markdown report into a styled, self-contained
    'Zero Trace // Red Team' themed HTML file and saves it to disk."""
    os.makedirs(output_dir, exist_ok=True)

    body_html = markdown.markdown(
        ai_markdown_text,
        extensions=["fenced_code", "tables", "sane_lists"]
    )

    final_html = HTML_TEMPLATE.format(
        target=target,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        model=model_name,
        body=body_html,
    )

    safe_name = target.replace("/", "_").replace(":", "_")
    file_path = os.path.join(output_dir, f"{safe_name}_report.html")

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(final_html)

    print(f"[+] HTML report saved -> {file_path}")
    return file_path