import os
import markdown
from datetime import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ZT-RECON Report — {target}</title>
<style>
    :root {{
        --bg: #0a0e0a;
        --panel: #10160f;
        --neon: #39ff14;
        --neon-dim: #1fae0d;
        --text: #c8ffcf;
        --danger: #ff3860;
        --warn: #ffd93b;
        --border: #1c2a1a;
    }}

    * {{ box-sizing: border-box; }}

    body {{
        background: var(--bg);
        color: var(--text);
        font-family: 'Courier New', Consolas, monospace;
        margin: 0;
        padding: 0;
        line-height: 1.6;
        background-image:
            linear-gradient(rgba(57,255,20,0.03) 1px, transparent 1px),
            linear-gradient(90deg, rgba(57,255,20,0.03) 1px, transparent 1px);
        background-size: 24px 24px;
    }}

    .header {{
        border-bottom: 1px solid var(--neon-dim);
        padding: 28px 40px;
        background: linear-gradient(180deg, #0d130c 0%, #0a0e0a 100%);
    }}

    .header h1 {{
        color: var(--neon);
        text-shadow: 0 0 8px rgba(57,255,20,0.6);
        margin: 0 0 6px 0;
        font-size: 28px;
        letter-spacing: 2px;
    }}

    .header .meta {{
        color: #7fa87a;
        font-size: 13px;
    }}

    .container {{
        max-width: 980px;
        margin: 0 auto;
        padding: 30px 40px 60px 40px;
    }}

    .panel {{
        background: var(--panel);
        border: 1px solid var(--border);
        border-left: 3px solid var(--neon);
        border-radius: 4px;
        padding: 24px 28px;
        margin-bottom: 0;
    }}

    h2 {{
        color: var(--neon);
        border-bottom: 1px dashed var(--border);
        padding-bottom: 8px;
        margin-top: 36px;
        font-size: 19px;
    }}

    h3 {{ color: #8fffb0; font-size: 16px; }}

    code, pre {{
        background: #060a06;
        color: #9dffb0;
        border: 1px solid var(--border);
        border-radius: 4px;
        padding: 2px 6px;
        font-size: 13.5px;
    }}

    pre {{ padding: 14px; overflow-x: auto; }}

    a {{ color: var(--neon); }}

    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 14px 0;
    }}

    th, td {{
        border: 1px solid var(--border);
        padding: 8px 12px;
        text-align: left;
        font-size: 13.5px;
    }}

    th {{ background: #0d140c; color: var(--neon); }}

    blockquote {{
        border-left: 3px solid var(--warn);
        margin: 10px 0;
        padding: 4px 16px;
        color: var(--warn);
        background: #14130a;
    }}

    .footer {{
        text-align: center;
        color: #4b6b48;
        font-size: 12px;
        margin-top: 50px;
        border-top: 1px solid var(--border);
        padding-top: 18px;
    }}

    ::selection {{ background: var(--neon); color: #000; }}
</style>
</head>
<body>
    <div class="header">
        <h1>&gt;&gt; ZT-RECON // SECURITY ASSESSMENT REPORT</h1>
        <div class="meta">
            TARGET: {target} &nbsp;|&nbsp; GENERATED: {timestamp} &nbsp;|&nbsp; ENGINE: {model}
        </div>
    </div>
    <div class="container">
        <div class="panel">
            {body}
        </div>
        <div class="footer">
            Generated by ZT-RECON — AI-Powered Automated Recon &amp; Exploitation Orchestrator.<br>
            For authorized security testing use only.
        </div>
    </div>
</body>
</html>
"""


def generate_html_report(target, ai_markdown_text, output_dir="./reports", model_name="unknown"):
    """Converts the AI-generated Markdown report into a styled, self-contained
    'Zero Trace' themed HTML file and saves it to disk."""
    os.makedirs(output_dir, exist_ok=True)

    body_html = markdown.markdown(
        ai_markdown_text,
        extensions=["fenced_code", "tables", "sane_lists"]
    )

    final_html = HTML_TEMPLATE.format(
        target=target,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        model=model_name,
        body=body_html,
    )

    safe_name = target.replace("/", "_").replace(":", "_")
    file_path = os.path.join(output_dir, f"{safe_name}_report.html")

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(final_html)

    print(f"[+] HTML report saved -> {file_path}")
    return file_path